<a href="https://colab.research.google.com/github/PandyaJeet/Python_Labwork/blob/main/hello.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<B>24BCA095</b>

In [5]:
import pandas as pd

In [6]:
#DataFrame
pd.DataFrame({'Apples' : [1], 'Bananas': [2]})
pd.DataFrame({'Apples' : [30], 'Bananas': [21]},index=["Useless"])

         Apples  Bananas
Useless      30       21

In [9]:
pd.Series([30,40,50],index=['Hello',"World","Po"])

Hello    30
World    40
Po       50
dtype: int64